"""entries table

Revision ID: 1b29cd248d61
Revises: 
Create Date: 2022-12-16 13:29:44.782946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b29cd248d61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=64), nullable=False),
    sa.Column('razon_social', sa.String(length=64), nullable=False),
    sa.Column('cod_banco', sa.String(length=64), nullable=False),
    sa.Column('banco', sa.String(length=64), nullable=False),
    sa.Column('tipo_cta', sa.String(length=64), nullable=False),
    sa.Column('num_cta', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_banco'), 'entry', ['banco'], unique=False)
    op.create_index(op.f('ix_entry_cod_banco'), 'entry', ['cod_banco'], unique=False)
    op.create_index(op.f('ix_entry_email'), 'entry', ['email'], unique=False)
    op.create_index(op.f('ix_entry_num_cta'), 'entry', ['num_cta'], unique=False)
    op.create_index(op.f('ix_entry_razon_social'), 'entry', ['razon_social'], unique=False)
    op.create_index(op.f('ix_entry_rut'), 'entry', ['rut'], unique=False)
    op.create_index(op.f('ix_entry_tipo_cta'), 'entry', ['tipo_cta'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_tipo_cta'), table_name='entry')
    op.drop_index(op.f('ix_entry_rut'), table_name='entry')
    op.drop_index(op.f('ix_entry_razon_social'), table_name='entry')
    op.drop_index(op.f('ix_entry_num_cta'), table_name='entry')
    op.drop_index(op.f('ix_entry_email'), table_name='entry')
    op.drop_index(op.f('ix_entry_cod_banco'), table_name='entry')
    op.drop_index(op.f('ix_entry_banco'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
